function ShowMatrix3D(A,x,y);
% Demonstraton of a 3x3-matrix
%
m=7; n=2;
a=A(1,1); b=A(1,2);    e=A(1,3);    e1=A(1,4);
c=A(2,1); d=A(2,2);    f=A(2,3);    f1=A(2,4);
g=A(3,1); h=A(3,2);    p=A(3,3);    p1=A(3,4);
g2=A(4,1); h2=A(4,2); p2=A(4,3);    p3=A(4,4);
detAs=number2str(det(A),m,n);
MT=['$$T=\left[\begin{array}{rrrr}',...
   number2str(a,m,n),'&',number2str(b,m,n),'&',number2str(e,m,n),...
     '&',number2str(e1,m,n),    '\\'...
   number2str(c,m,n),'&',number2str(d,m,n),'&',number2str(f,m,n),...
     '&',number2str(f1,m,n),    '\\'...
   number2str(g,m,n),'&',number2str(h,m,n),'&',number2str(p,m,n),...
     '&',number2str(p1,m,n),    '\\'...
   number2str(g2,m,n),'&',number2str(h2,m,n),'&',number2str(p2,m,n),...
     '&',number2str(p3,m,n),    '\\'...  
              '\end{array}\right]$$'];
%TXT={MT;['det(A)=',detAs]};          
text('Interpreter','latex','String',MT,...
   'Position',[x,y],'FontSize',18,'FontWeight','bold','Color','k')
end

